config/routes.rb
ReadOMeter::Application.routes.draw do

  get 'books/index'

  resources :books
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/books',   :to => 'books#index'
  match '/newbook', :to => 'books#new'
  match '/signup',	:to => 'users#new'
  match '/signin',	:to => 'sessions#new'
  match '/signout',	:to => 'sessions#destroy'
  match '/contact',	:to => 'pages#contact'
  match '/about',	:to => 'pages#about'
  match '/help',	:to => 'pages#help'
  root			:to => 'pages#home'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  author      :string(255)
#  total_pages :integer
#  read_pages  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Book < ActiveRecord::Base
  attr_accessible :title, :author, :total_pages, :read_pages

  validates :title, :presence => true

  validates :author, :presence => true

  validates_numericality_of :total_pages,
                            :greater_than => 0

  validates_numericality_of :read_pages,
                            :equal_to => 0,
                            :on => :create

  validates_numericality_of :read_pages,
                            :less_than_or_equal_to => :total_pages,
                            :on => :update
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, 	  :presence => true,
  		   	  :length   => { :maximum => 50 }
  
  validates :email, 	  :presence   => true,
  		    	  :format     => { :with => email_regex },
		    	  :uniqueness => { :case_sensitive => false }
  
  validates :password, 	  :presence     => true,
  			  :confirmation => true,
  			  :length       => { :within => 6..40 }
  
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @title = @book.title
  end

  def new
    @book = Book.new
    @title = "New book"
  end

  def index
    @books = Book.all
    @title = "All books"
  end

  def create
    @book = Book.new(params[:book])
    @book.read_pages = 0
    if @book.save
      flash[:success] = "Successfully added a new book!"
      redirect_to @book
    else
      @title = "New book"
      render 'new'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
    			     params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Read-O-Meter!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a image tag for the logo
  def logo
    image_tag("logo.png", :alt => "Read-O-Meter", :class => "round")
  end

  # Return a title on a per-page basis.
  def title
    base_title = "Read-O-Meter: Track your reading"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
    					    :class => 'gravatar',
					    :gravatar => options)
  end
end

app/views/books/index.html.erb
<h1>books</h1>
<% @books.each do |book| %>
    <ul>
        <li><%= link_to book.title, book_path(book.id) %></li>
    </ul>
<% end %>

app/views/books/new.html.erb
<h1>Add new book</h1>
<%= form_for(@book) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :total_pages %><br />
    <%= f.text_field :total_pages %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/books/show.html.erb
<table class="book" summary="Book information">
  <tr>
    <td class="main">
      <h1><%= @book.title %></h1>
      <p>Author: <%= @book.author %></p>
      <p>Total Pages: <%= @book.total_pages %></p>
      <p>Read Pages: <%= @book.read_pages %></p>
      <p>Progress: <%= (@book.read_pages * 100) / @book.total_pages %>%</p>
    </td>
  </tr>
</table>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  This is the about page for the <%= link_to 'Read-O-Meter', root_path %>
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  This is the contact page for the <%= link_to 'Read-O-Meter', root_path %>
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  This is the help page for the <%= link_to 'Read-O-Meter', root_path  %>
</p>

app/views/pages/home.html.erb
<h1>Read-O-Meter</h1>
<p>
  Not a member yet? Sign up now and start tracking your reading!
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_new_book_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %>
        prohibited this book from saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/new.html.erb
<h1>Sing up</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>